import 'dart:async';

import 'package:esme2526/datas/bet_repository_interface.dart';
import 'package:esme2526/models/bet.dart';
import 'package:esme2526/models/data_bet.dart';

class BetRepository implements BetRepositoryInterface {
  StreamController<List<Bet>> betsStreamController = StreamController<List<Bet>>();

  @override
  Future<void> saveBets(List<Bet> bets) async {
    betsStreamController.add(bets);
  }

  @override
  Stream<List<Bet>> getBetsStream() async* {
    List<Bet> bets = await getBets();
    List<Bet> betsList = [];

    for (int i = 0; i < bets.length; i++) {
      await Future.delayed(Duration(seconds: 4));
      betsList.add(bets[i]);
      //   yield betsList;
    }
  }

  @override
  Future<List<Bet>> getBets() async {
    return [
      Bet(
        id: "1",
        title: "Match de Football - Coupe du Monde",
        description: "Parier sur le vainqueur du match France vs Brésil",
        odds: 2,
        startTime: DateTime.now(),
        endTime: DateTime.now().add(Duration(hours: 2)),
        dataBet: DataBet(id: "1", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "2",
        title: "Tennis - Finale Roland Garros",
        description: "Qui remportera le titre cette année?",
        odds: 3,
        startTime: DateTime.now(),
        endTime: DateTime.now().add(Duration(hours: 3)),
        dataBet: DataBet(id: "2", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "3",
        title: "Basket - NBA Finals",
        description: "Prédire le score final de la série",
        odds: 4,
        startTime: DateTime.now(),
        endTime: DateTime.now().add(Duration(hours: 4)),
        dataBet: DataBet(id: "3", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "4",
        title: "Formule 1 - Grand Prix de Monaco",
        description: "Quel pilote obtiendra la pole position?",
        odds: 5,
        startTime: DateTime.now(),
        endTime: DateTime.now().add(Duration(hours: 1)),
        dataBet: DataBet(id: "4", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "5",
        title: "Rugby - Tournoi des 6 Nations",
        description: "Parier sur l'équipe qui remportera le tournoi",
        odds: 6,
        startTime: DateTime.now().add(Duration(hours: 1)),
        endTime: DateTime.now().add(Duration(hours: 5)),
        dataBet: DataBet(id: "5", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "6",
        title: "E-sport - Championnat League of Legends",
        description: "Quelle équipe remportera la finale?",
        odds: 7,
        startTime: DateTime.now(),
        endTime: DateTime.now().add(Duration(hours: 6)),
        dataBet: DataBet(id: "6", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "7",
        title: "Hockey - Ligue Nationale",
        description: "Prédire le nombre de buts dans le match",
        odds: 3,
        startTime: DateTime.now().add(Duration(hours: 2)),
        endTime: DateTime.now().add(Duration(hours: 4)),
        dataBet: DataBet(id: "7", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "8",
        title: "Boxe - Combat du Siècle",
        description: "Qui gagnera par KO dans les 5 premiers rounds?",
        odds: 8,
        startTime: DateTime.now(),
        endTime: DateTime.now().add(Duration(hours: 3)),
        dataBet: DataBet(id: "8", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "9",
        title: "Golf - Masters Tournament",
        description: "Quel golfeur terminera avec le meilleur score?",
        odds: 5,
        startTime: DateTime.now().add(Duration(hours: 1)),
        endTime: DateTime.now().add(Duration(hours: 7)),
        dataBet: DataBet(id: "9", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "10",
        title: "Natation - Championnats du Monde",
        description: "Prédire le temps du record du monde du 100m nage libre",
        odds: 10,
        startTime: DateTime.now(),
        endTime: DateTime.now().add(Duration(hours: 2)),
        dataBet: DataBet(id: "10", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "11",
        title: "Cricket - Coupe du Monde",
        description: "Vainqueur du match entre Inde et Australie",
        odds: 2.5,
        startTime: DateTime.now().add(Duration(hours: 2)),
        endTime: DateTime.now().add(Duration(hours: 8)),
        dataBet: DataBet(id: "11", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "12",
        title: "Baseball - World Series",
        description: "Équipe qui marquera le premier point",
        odds: 1.8,
        startTime: DateTime.now().add(Duration(hours: 3)),
        endTime: DateTime.now().add(Duration(hours: 9)),
        dataBet: DataBet(id: "12", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "13",
        title: "Volleyball - Championnat Olympique",
        description: "Quelle équipe gagnera la manche 3?",
        odds: 2.2,
        startTime: DateTime.now().add(Duration(hours: 1)),
        endTime: DateTime.now().add(Duration(hours: 5)),
        dataBet: DataBet(id: "13", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "14",
        title: "Athlétisme - 100m sprint",
        description: "Temps de victoire inférieur à 9.8 secondes?",
        odds: 3.5,
        startTime: DateTime.now().add(Duration(hours: 4)),
        endTime: DateTime.now().add(Duration(hours: 6)),
        dataBet: DataBet(id: "14", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "15",
        title: "Cyclisme - Tour de France",
        description: "Porte le maillot jaune après la 12ème étape",
        odds: 4.2,
        startTime: DateTime.now().add(Duration(hours: 5)),
        endTime: DateTime.now().add(Duration(days: 1)),
        dataBet: DataBet(id: "15", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "16",
        title: "Ski - Coupe du Monde",
        description: "Gagnant de la descente masculine",
        odds: 3.8,
        startTime: DateTime.now().add(Duration(hours: 2)),
        endTime: DateTime.now().add(Duration(hours: 4)),
        dataBet: DataBet(id: "16", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "17",
        title: "Handball - Ligue des Champions",
        description: "Score total des deux équipes dans la finale",
        odds: 2.7,
        startTime: DateTime.now().add(Duration(hours: 6)),
        endTime: DateTime.now().add(Duration(hours: 8)),
        dataBet: DataBet(id: "17", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "18",
        title: "Surf - Championnat du Monde",
        description: "Meilleur surfeur de la compétition",
        odds: 5.5,
        startTime: DateTime.now().add(Duration(hours: 1)),
        endTime: DateTime.now().add(Duration(hours: 12)),
        dataBet: DataBet(id: "18", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "19",
        title: "Badminton - Championnat du Monde",
        description: "Gagnant du simple masculin",
        odds: 3.2,
        startTime: DateTime.now().add(Duration(hours: 3)),
        endTime: DateTime.now().add(Duration(hours: 7)),
        dataBet: DataBet(id: "19", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "20",
        title: "Escalade - Championnat Olympique",
        description: "Premier grimpeur à atteindre le sommet",
        odds: 4.8,
        startTime: DateTime.now().add(Duration(hours: 2)),
        endTime: DateTime.now().add(Duration(hours: 6)),
        dataBet: DataBet(id: "20", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "21",
        title: "Automobile - Rallye Monte Carlo",
        description: "Pilote gagnant de la catégorie WRC",
        odds: 6.1,
        startTime: DateTime.now().add(Duration(hours: 8)),
        endTime: DateTime.now().add(Duration(hours: 12)),
        dataBet: DataBet(id: "21", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "22",
        title: "Football Américain - Super Bowl",
        description: "Équipe qui marquera en premier",
        odds: 1.9,
        startTime: DateTime.now().add(Duration(hours: 4)),
        endTime: DateTime.now().add(Duration(hours: 8)),
        dataBet: DataBet(id: "22", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "23",
        title: "Hockey sur Glace - Coupe Stanley",
        description: "Nombre de buts dans le 3e tiers-temps",
        odds: 2.9,
        startTime: DateTime.now().add(Duration(hours: 1)),
        endTime: DateTime.now().add(Duration(hours: 3)),
        dataBet: DataBet(id: "23", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "24",
        title: "Rugby à VII - Championnat du Monde",
        description: "Gagnant de la finale masculine",
        odds: 3.4,
        startTime: DateTime.now().add(Duration(hours: 2)),
        endTime: DateTime.now().add(Duration(hours: 5)),
        dataBet: DataBet(id: "24", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "25",
        title: "Tir à l'Arc - Championnat Olympique",
        description: "Score final du gagnant en qualification",
        odds: 4.3,
        startTime: DateTime.now().add(Duration(hours: 3)),
        endTime: DateTime.now().add(Duration(hours: 6)),
        dataBet: DataBet(id: "25", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "26",
        title: "Gymnastique - Championnat du Monde",
        description: "Score de perfection du saut de cheval",
        odds: 5.2,
        startTime: DateTime.now().add(Duration(hours: 1)),
        endTime: DateTime.now().add(Duration(hours: 4)),
        dataBet: DataBet(id: "26", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "27",
        title: "Saut à Ski - Coupe du Monde",
        description: "Distance du saut gagnant",
        odds: 3.7,
        startTime: DateTime.now().add(Duration(hours: 5)),
        endTime: DateTime.now().add(Duration(hours: 8)),
        dataBet: DataBet(id: "27", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "28",
        title: "Biathlon - Championnat du Monde",
        description: "Temps gagnant sur 20km individuel",
        odds: 4.6,
        startTime: DateTime.now().add(Duration(hours: 6)),
        endTime: DateTime.now().add(Duration(hours: 10)),
        dataBet: DataBet(id: "28", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "29",
        title: "Patinage Artistique - Grand Prix",
        description: "Score technique du gagnant",
        odds: 5.1,
        startTime: DateTime.now().add(Duration(hours: 2)),
        endTime: DateTime.now().add(Duration(hours: 5)),
        dataBet: DataBet(id: "29", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "30",
        title: "Water-polo - Championnat du Monde",
        description: "Nombre total de buts dans la finale",
        odds: 2.8,
        startTime: DateTime.now().add(Duration(hours: 3)),
        endTime: DateTime.now().add(Duration(hours: 6)),
        dataBet: DataBet(id: "30", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "31",
        title: "Canoë-Kayak - Championnat Olympique",
        description: "Temps gagnant sur 1000m K1",
        odds: 3.9,
        startTime: DateTime.now().add(Duration(hours: 1)),
        endTime: DateTime.now().add(Duration(hours: 4)),
        dataBet: DataBet(id: "31", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "32",
        title: "Judo - Grand Slam",
        description: "Poids moyen - gagnant du combat",
        odds: 4.4,
        startTime: DateTime.now().add(Duration(hours: 2)),
        endTime: DateTime.now().add(Duration(hours: 5)),
        dataBet: DataBet(id: "32", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "33",
        title: "Taekwondo - Championnat du Monde",
        description: "Combattant gagnant dans la catégorie 68kg",
        odds: 3.1,
        startTime: DateTime.now().add(Duration(hours: 4)),
        endTime: DateTime.now().add(Duration(hours: 7)),
        dataBet: DataBet(id: "33", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "34",
        title: "Boxe Olympique - Légère",
        description: "Combattant qui gagne par décision",
        odds: 2.6,
        startTime: DateTime.now().add(Duration(hours: 3)),
        endTime: DateTime.now().add(Duration(hours: 6)),
        dataBet: DataBet(id: "34", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "35",
        title: "Lutte - Championnat du Monde",
        description: "Temps du combat gagnant en finale",
        odds: 4.9,
        startTime: DateTime.now().add(Duration(hours: 5)),
        endTime: DateTime.now().add(Duration(hours: 8)),
        dataBet: DataBet(id: "35", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "36",
        title: "Aviron - Championnat du Monde",
        description: "Équipe gagnante des 2 sans barreur",
        odds: 3.3,
        startTime: DateTime.now().add(Duration(hours: 2)),
        endTime: DateTime.now().add(Duration(hours: 5)),
        dataBet: DataBet(id: "36", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "37",
        title: "Tennis de Table - Championnat du Monde",
        description: "Score final de la finale (nombre de sets)",
        odds: 4.1,
        startTime: DateTime.now().add(Duration(hours: 1)),
        endTime: DateTime.now().add(Duration(hours: 4)),
        dataBet: DataBet(id: "37", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "38",
        title: "Haltérophilie - Championnat du Monde",
        description: "Total olympique du vainqueur en -89kg",
        odds: 5.8,
        startTime: DateTime.now().add(Duration(hours: 3)),
        endTime: DateTime.now().add(Duration(hours: 6)),
        dataBet: DataBet(id: "38", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "39",
        title: "Squash - Championnat du Monde",
        description: "Nombre de sets dans la finale masculine",
        odds: 3.6,
        startTime: DateTime.now().add(Duration(hours: 4)),
        endTime: DateTime.now().add(Duration(hours: 8)),
        dataBet: DataBet(id: "39", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "40",
        title: "Course à pied - Marathon",
        description: "Temps gagnant inférieur à 2h05min?",
        odds: 2.4,
        startTime: DateTime.now().add(Duration(hours: 6)),
        endTime: DateTime.now().add(Duration(hours: 10)),
        dataBet: DataBet(id: "40", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "41",
        title: "Football - Ligue des Champions",
        description: "Équipe qui ouvre le score",
        odds: 2.3,
        startTime: DateTime.now().add(Duration(hours: 1)),
        endTime: DateTime.now().add(Duration(hours: 3)),
        dataBet: DataBet(id: "41", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "42",
        title: "Tennis - US Open",
        description: "Gagnant du simple féminin",
        odds: 4.7,
        startTime: DateTime.now().add(Duration(hours: 8)),
        endTime: DateTime.now().add(Duration(hours: 12)),
        dataBet: DataBet(id: "42", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "43",
        title: "Basketball - EuroLeague",
        description: "Équipe qui domine en rebonds",
        odds: 3.0,
        startTime: DateTime.now().add(Duration(hours: 2)),
        endTime: DateTime.now().add(Duration(hours: 4)),
        dataBet: DataBet(id: "43", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "44",
        title: "Formule 1 - Grand Prix de Singapour",
        description: "Vainqueur du sprint samedi",
        odds: 5.3,
        startTime: DateTime.now().add(Duration(hours: 5)),
        endTime: DateTime.now().add(Duration(hours: 7)),
        dataBet: DataBet(id: "44", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "45",
        title: "Rugby - Coupe du Monde",
        description: "Nombre total d'essais dans le quart de finale",
        odds: 4.0,
        startTime: DateTime.now().add(Duration(hours: 3)),
        endTime: DateTime.now().add(Duration(hours: 7)),
        dataBet: DataBet(id: "45", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "46",
        title: "E-sport - Valorant Champions Tour",
        description: "Équipe qui gagne sans perdre un round",
        odds: 6.5,
        startTime: DateTime.now().add(Duration(hours: 4)),
        endTime: DateTime.now().add(Duration(hours: 6)),
        dataBet: DataBet(id: "46", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "47",
        title: "Hockey sur Gazon - Championnat du Monde",
        description: "Gagnant de la finale féminine",
        odds: 3.8,
        startTime: DateTime.now().add(Duration(hours: 2)),
        endTime: DateTime.now().add(Duration(hours: 5)),
        dataBet: DataBet(id: "47", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "48",
        title: "Boxe - Championnat du Monde Professionnel",
        description: "Temps de l'arrêt du combat",
        odds: 5.6,
        startTime: DateTime.now().add(Duration(hours: 6)),
        endTime: DateTime.now().add(Duration(hours: 8)),
        dataBet: DataBet(id: "48", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "49",
        title: "Golf - Open Championship",
        description: "Nombre de coups du gagnant par rapport au par",
        odds: 4.5,
        startTime: DateTime.now().add(Duration(hours: 7)),
        endTime: DateTime.now().add(Duration(days: 1)),
        dataBet: DataBet(id: "49", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
      Bet(
        id: "50",
        title: "Natation - Championnats Européens",
        description: "Quel nageur établit le record du 200m dos?",
        odds: 6.2,
        startTime: DateTime.now().add(Duration(hours: 1)),
        endTime: DateTime.now().add(Duration(hours: 4)),
        dataBet: DataBet(id: "50", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", imgUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
      ),
    ];
  }
}
