// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:esme2526/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BetAdapter());
    registerAdapter(DataBetAdapter());
    registerAdapter(UserBetAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BetAdapter());
    registerAdapter(DataBetAdapter());
    registerAdapter(UserBetAdapter());
  }
}
